services:
  web:
    container_name: DesarrolloEmpresarial
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      NODE_ENV: development
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev -- --hostname 0.0.0.0 --port 3000"